### ISSUE TITLE
Request: The time between button presses for arcade sticks

### ISSUE THREAD

**Issue by HippoLOL** [chrizonix/XInputTest#4]
Any chance you could add an arcade stick test to see the Hz rating at the moment it uses left stick but button presses would be appreciated, since arcade sticks use DPAD and buttons.

**Comment by chrizonix** [comment]
Hi @HippoLOL,

I can create a version for you, that uses the left stick, instead of the right stick (please tell me, if you would like so).
But using button presses is currently impossible, because of how the program works.

To test the input latency (or polling rate), I need either a.) several distinct input states (of the gamepad), or b.)
a device that can measure the time between a button press and the actual signal on the device driver.

Since it's impossible to know, when a button was pressed (without an external device),
the only solution is to compare two different gamepad states with each other.

So the program polls the gamepad several thousand times a second, and compares the time between two distinct gamepad states, and calculates the latency and polling rate. But this means, that the gamepad has to produce at least 1000 different gamepad states every second (if you have a polling rate of 1000 Hz, or 250 states when using 250 Hz).

When moving the joystick quickly, it is possible to produce 1000 different gamepad states every second.
But it's not possible to press a button 1000 times a second, even if the arcade stick would use DPAD buttons.

So if you can only press the DPAD buttons 20 times a second, my program would calculate 20 Hz polling rate (50 ms Latency).
Which, of course, is wrong because the test was limited by the number of times a human can press a button.

Hope this explanation helps.

**Comment by HippoLOL** [comment]
thank you.
